version: '3'

#volumes:
#  postres-db:
#    external: true

services:


  db:
    container_name: postgres_database
    image: postgres:15.1
    volumes:
      #- postres-db:/var/lib/postgresql/data
      - ./postgresdb:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=123456

  pgadmin:
    depends_on:
      - db
    image: dpage/pgadmin4:6.17
    ports:
      - "8080:80"
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_PASSWORD=123456
      - PGADMIN_DEFAULT_EMAIL=superman@google.com