version: '3'

volumes:
  prometheus-data:
    driver: local
  grafana-data:
    driver: local

services:
### Grafana ################################################
  grafana:
    container_name: grafana_monitoring
    image: grafana/grafana:7.0.6
    ports:
      - 3000:3000
    volumes:
      - grafana-data:/var/lib/grafana
    restart: unless-stopped

### Prometheus ################################################
  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    volumes:
      - prometheus-data:/etc/prometheus