version: '3.1'

networks:
  backend:
    driver: bridge

volumes:
  prometheus-data:
    driver: local
  grafana-data:
    driver: local
  mysql-data:
    driver: local
  phpmyadmin:
    driver: local

services:

### MySQL ################################################
  mysql:
    image: mysql:latest
    container_name: adherencedb
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - TZ=America/Panama
    command: ['mysqld','--character-set-server=utf8','--default-authentication-plugin=mysql_native_password']
    volumes:
      - mysql-data:/var/lib/mysql
      - ./docker-entrypoint:/docker-entrypoint
    restart: always
    ports:
      - "3306:3306"
    networks:
      - backend

### phpMyAdmin ###########################################
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=root
      - MAX_EXECUTION_TIME=600
      - MEMORY_LIMIT=256M
      - UPLOAD_LIMIT=2G
    ports:
      - 8077:80
    depends_on:
      - mysql
    networks:
      - backend

### Grafana ################################################
  grafana:
    image: grafana/grafana:latest
    container_name: grafana_monitoring
    ports:
      - 3000:3000
    depends_on:
      - mysql
    volumes:
      - ./docker-entrypoint:/docker-entrypoint
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - grafana-data:/var/lib/grafana
    restart: unless-stopped
    networks:
      - backend

### Prometheus ################################################
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    networks:
      - backend